name: Update GitHub Contributions

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 12 * * *'  # 每天UTC时间12:00运行（北京时间20:00）
    
permissions:
  contents: write  # 确保有写入权限
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install --only-upgrade python3-pip
        if [ -f requirements.txt ]; then sudo pip install -r requirements.txt; fi
      
    - name: Run Python script
      run: |
        sudo python Github_contributions.py
      
    - name: add and change
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add github_contributions_*.json  # 添加生成的文件
        git commit -m "Update Github Contribution [action]" || echo "No changes to commit"
      continue-on-error: true
      
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
