name: Update GitHub Contributions

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 12 * * *'  # 每天UTC时间12:00运行（北京时间20:00）

jobs:
  update-contributions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run script
      env:
        GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
      run: python Github_contributions.py
      
    - name: Commit changes
      run: |
         git config --global user.name 'GitHub Action'
         git config --global user.email 'action@github.com'
         git commit -m "Update Github Contribution [action]" || echo "No changes to commit"
      continue-on-error: true

    - name: Push changes
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push origin main
